### ISSUE TITLE
Setting up Private Server

### ISSUE THREAD

**Issue by Dichill** [friedkeenan/tfm-secrets-leaker#2]
Hello! Im using this server files from: https://github.com/3e08488f9bcc2dd50192b3db89f6612c/SWF-Database-and-Tools/blob/main/Sources/1.680.rar by Paranormal Activity. I tried using this tool to replace the values in the infoSWF.json and I also used TFM-Proxy-Loader to direct it to my localhost. However upon opening TFM, it says that "incorrect version, try to reload the game."

After further investigation, maybe it has something to do with the function "SendCorrectVersion()" being outdated as the server files are 3 years ago.

Here is the code for the function as it might help.
```python
def sendCorrectVersion(self, community="en"):
        self.sendPacket(
            Identifiers.send.Correct_Version,
            ByteArray()
            .writeInt(len(self.server.players))
            .writeUTF(community)
            .writeUTF("")
            .writeInt(self.server.authKey)
            .writeBoolean(False)
            .toByteArray(),
        )
        self.sendPacket(
            Identifiers.send.Banner_Login,
            ByteArray()
            .writeBoolean(True)
            .writeByte(self.server.adventureID)
            .writeShort(256)
            .toByteArray(),
        )
        self.sendPacket(
            Identifiers.send.Image_Login,
            ByteArray().writeUTF(self.server.adventureIMG).toByteArray(),
        )
```

I don't really know anything about packets, networking and all of that, but I've tried researching and its still quite confusing for me.
Any help is appreciated, thank you!

**Comment by friedkeenan** [comment]
This issue is outside the scope of this project. I would say you should seek help elsewhere, such as from the creator of those files themselves.
